### PR TITLE
Refactor CAT interface to comply with Cloudlog V2

### PR DESCRIPTION
**Pull request by phl0**
This updates CloudLogCatQt to cope with the latest changes in Cloudlog's API that where introduced by @kb-light. See https://github.com/magicbug/Cloudlog/pull/1582.

Squashed commit of the following:

commit 125fac83c0410adddcbec857ea6dd1d8a2bf234e
Author: Florian Wolters <github@florian-wolters.de>
Date:   Thu Sep 29 13:20:20 2022 +0200

    Remove separate uplink values for frequency and mode

commit b9f38c7efd3c7228b3b8ea2ed11fc3110c3ad293
Author: Florian Wolters <github@florian-wolters.de>
Date:   Thu Sep 29 11:54:09 2022 +0200

    Prevent upload until nec. varialbes are set

commit 906979fce404bc3674c5426e5915e23daf1dea07
Author: Florian Wolters <github@florian-wolters.de>
Date:   Wed Sep 21 11:40:24 2022 +0200

    Set placeholders and input contraints

commit 597e0ddeb3f47753d0c1b8e5cd9a0406b7821c16
Author: Florian Wolters <github@florian-wolters.de>
Date:   Tue Sep 20 22:43:36 2022 +0200

    Add editable identifier

### CODE REVIEW

**Comment by kb-light** [comment]
Just take into account that this will break backward compatibility with Cloudlog V1

**Comment by phl0** [comment]
True. I hope for soon release of V2. I think the API stuff was the last @magicbug was waiting for. ✌️

**Comment by myzinsky** [comment]
So shall we apply this?

**Comment by phl0** [comment]
> So shall we apply this?

Yes yes yes :)

**Pull request merged**
